export { default as About } from './about2-2.png';
export { default as Illustr } from './illustration1.png';
export { default as Logo } from './logo.png';
export { default as f1 } from './feature1.png';
export { default as f2 } from './feature2.png';
export { default as f3 } from './feature3.png';
export { default as rocket } from './rocket.png';
export { default as process } from './process1.png';
export { default as illustration } from './illustration21.png';
